language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules
script:
  - npm run flow-typed-install
  - npm run flow
  - npm run lint:tests -- --max-warnings=0
  - npm run build
  - npm test -- --coverage
deploy:
  provider: pages
  edge: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
after_script:
  - npm run codecov