language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm run lint:tests -- --max-warnings=0
  - npm test -- --coverage
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
after_script:
  - npm run codecov